services:
mysql:
  image: mysql:9.2.0
  container_name: mysql-container
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: ecommerce
    MYSQL_USER: root
    MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
