server:
  port: 5000
  mode: "prod"

mysql:
  url: root:password@tcp(127.0.0.1:3306)/ecommerce
  # url: root:password@tcp(mysql-container:3306)/ecommerce
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 60
database:
  # - url: mysql://root:password@localhost:3306/ecommerce
  # - url: mysql://duc:password@localhost:3306/order
security:
  jwt:
    key: secret
redis:
  # host: redis-container
  host: 127.0.0.1
  port: 6379
  password:
  database: 0
elasticsearch:
  user: admin
rabbitMQ:
  user: admin
kafka:
  user: admin
logger:
  log_level: debug
  file_log_name: "./storages/logs/dev.xxx.log"
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true
