server:
  port: 5000
mysql:
  url: mysql://root:password@localhost:3306/ecommerce
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 60
database:
  - url: mysql://root:password@localhost:3306/ecommerce
  - url: mysql://duc:password@localhost:3306/order
security:
  jwt:
    key: secret
redis:
  user: admin
elasticsearch:
  user: admin
rabbitMQ:
  user: admin
kafka:
  user: admin
