server:
  port: 5000
database:
  - url: mysql://root:password@localhost:3306/ecommerce
  - url: mysql://duc:password@localhost:3306/order
security:
  jwt:
    key: secret
redis:
  user: admin
elasticsearch:
  user: admin
rabbitMQ:
  user: admin
kafka:
  user: admin
